// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.mwr.mercury;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string section = 1;
    boolean hasSection();
    String getSection();
    
    // optional string function = 2;
    boolean hasFunction();
    String getFunction();
    
    // repeated .com.mwr.mercury.KVPair args = 3;
    java.util.List<com.mwr.mercury.Message.KVPair> 
        getArgsList();
    com.mwr.mercury.Message.KVPair getArgs(int index);
    int getArgsCount();
    java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
        getArgsOrBuilderList();
    com.mwr.mercury.Message.KVPairOrBuilder getArgsOrBuilder(
        int index);
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string section = 1;
    public static final int SECTION_FIELD_NUMBER = 1;
    private java.lang.Object section_;
    public boolean hasSection() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSection() {
      java.lang.Object ref = section_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          section_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSectionBytes() {
      java.lang.Object ref = section_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        section_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string function = 2;
    public static final int FUNCTION_FIELD_NUMBER = 2;
    private java.lang.Object function_;
    public boolean hasFunction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFunction() {
      java.lang.Object ref = function_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          function_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFunctionBytes() {
      java.lang.Object ref = function_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        function_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.mwr.mercury.KVPair args = 3;
    public static final int ARGS_FIELD_NUMBER = 3;
    private java.util.List<com.mwr.mercury.Message.KVPair> args_;
    public java.util.List<com.mwr.mercury.Message.KVPair> getArgsList() {
      return args_;
    }
    public java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
        getArgsOrBuilderList() {
      return args_;
    }
    public int getArgsCount() {
      return args_.size();
    }
    public com.mwr.mercury.Message.KVPair getArgs(int index) {
      return args_.get(index);
    }
    public com.mwr.mercury.Message.KVPairOrBuilder getArgsOrBuilder(
        int index) {
      return args_.get(index);
    }
    
    private void initFields() {
      section_ = "";
      function_ = "";
      args_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getArgsCount(); i++) {
        if (!getArgs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSectionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFunctionBytes());
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeMessage(3, args_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSectionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFunctionBytes());
      }
      for (int i = 0; i < args_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, args_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mwr.mercury.Message.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mwr.mercury.Message.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mwr.mercury.Message.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Request_fieldAccessorTable;
      }
      
      // Construct using com.mwr.mercury.Message.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArgsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        section_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        function_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (argsBuilder_ == null) {
          args_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          argsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mwr.mercury.Message.Request.getDescriptor();
      }
      
      public com.mwr.mercury.Message.Request getDefaultInstanceForType() {
        return com.mwr.mercury.Message.Request.getDefaultInstance();
      }
      
      public com.mwr.mercury.Message.Request build() {
        com.mwr.mercury.Message.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mwr.mercury.Message.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mwr.mercury.Message.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mwr.mercury.Message.Request buildPartial() {
        com.mwr.mercury.Message.Request result = new com.mwr.mercury.Message.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.section_ = section_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.function_ = function_;
        if (argsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            args_ = java.util.Collections.unmodifiableList(args_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.args_ = args_;
        } else {
          result.args_ = argsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mwr.mercury.Message.Request) {
          return mergeFrom((com.mwr.mercury.Message.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mwr.mercury.Message.Request other) {
        if (other == com.mwr.mercury.Message.Request.getDefaultInstance()) return this;
        if (other.hasSection()) {
          setSection(other.getSection());
        }
        if (other.hasFunction()) {
          setFunction(other.getFunction());
        }
        if (argsBuilder_ == null) {
          if (!other.args_.isEmpty()) {
            if (args_.isEmpty()) {
              args_ = other.args_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureArgsIsMutable();
              args_.addAll(other.args_);
            }
            onChanged();
          }
        } else {
          if (!other.args_.isEmpty()) {
            if (argsBuilder_.isEmpty()) {
              argsBuilder_.dispose();
              argsBuilder_ = null;
              args_ = other.args_;
              bitField0_ = (bitField0_ & ~0x00000004);
              argsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArgsFieldBuilder() : null;
            } else {
              argsBuilder_.addAllMessages(other.args_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getArgsCount(); i++) {
          if (!getArgs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              section_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              function_ = input.readBytes();
              break;
            }
            case 26: {
              com.mwr.mercury.Message.KVPair.Builder subBuilder = com.mwr.mercury.Message.KVPair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addArgs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string section = 1;
      private java.lang.Object section_ = "";
      public boolean hasSection() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSection() {
        java.lang.Object ref = section_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          section_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSection(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        section_ = value;
        onChanged();
        return this;
      }
      public Builder clearSection() {
        bitField0_ = (bitField0_ & ~0x00000001);
        section_ = getDefaultInstance().getSection();
        onChanged();
        return this;
      }
      void setSection(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        section_ = value;
        onChanged();
      }
      
      // optional string function = 2;
      private java.lang.Object function_ = "";
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFunction() {
        java.lang.Object ref = function_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          function_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFunction(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        function_ = value;
        onChanged();
        return this;
      }
      public Builder clearFunction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        function_ = getDefaultInstance().getFunction();
        onChanged();
        return this;
      }
      void setFunction(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        function_ = value;
        onChanged();
      }
      
      // repeated .com.mwr.mercury.KVPair args = 3;
      private java.util.List<com.mwr.mercury.Message.KVPair> args_ =
        java.util.Collections.emptyList();
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          args_ = new java.util.ArrayList<com.mwr.mercury.Message.KVPair>(args_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder> argsBuilder_;
      
      public java.util.List<com.mwr.mercury.Message.KVPair> getArgsList() {
        if (argsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(args_);
        } else {
          return argsBuilder_.getMessageList();
        }
      }
      public int getArgsCount() {
        if (argsBuilder_ == null) {
          return args_.size();
        } else {
          return argsBuilder_.getCount();
        }
      }
      public com.mwr.mercury.Message.KVPair getArgs(int index) {
        if (argsBuilder_ == null) {
          return args_.get(index);
        } else {
          return argsBuilder_.getMessage(index);
        }
      }
      public Builder setArgs(
          int index, com.mwr.mercury.Message.KVPair value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.set(index, value);
          onChanged();
        } else {
          argsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setArgs(
          int index, com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.set(index, builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addArgs(com.mwr.mercury.Message.KVPair value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.add(value);
          onChanged();
        } else {
          argsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addArgs(
          int index, com.mwr.mercury.Message.KVPair value) {
        if (argsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgsIsMutable();
          args_.add(index, value);
          onChanged();
        } else {
          argsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addArgs(
          com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.add(builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addArgs(
          int index, com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.add(index, builderForValue.build());
          onChanged();
        } else {
          argsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllArgs(
          java.lang.Iterable<? extends com.mwr.mercury.Message.KVPair> values) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          super.addAll(values, args_);
          onChanged();
        } else {
          argsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearArgs() {
        if (argsBuilder_ == null) {
          args_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          argsBuilder_.clear();
        }
        return this;
      }
      public Builder removeArgs(int index) {
        if (argsBuilder_ == null) {
          ensureArgsIsMutable();
          args_.remove(index);
          onChanged();
        } else {
          argsBuilder_.remove(index);
        }
        return this;
      }
      public com.mwr.mercury.Message.KVPair.Builder getArgsBuilder(
          int index) {
        return getArgsFieldBuilder().getBuilder(index);
      }
      public com.mwr.mercury.Message.KVPairOrBuilder getArgsOrBuilder(
          int index) {
        if (argsBuilder_ == null) {
          return args_.get(index);  } else {
          return argsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
           getArgsOrBuilderList() {
        if (argsBuilder_ != null) {
          return argsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(args_);
        }
      }
      public com.mwr.mercury.Message.KVPair.Builder addArgsBuilder() {
        return getArgsFieldBuilder().addBuilder(
            com.mwr.mercury.Message.KVPair.getDefaultInstance());
      }
      public com.mwr.mercury.Message.KVPair.Builder addArgsBuilder(
          int index) {
        return getArgsFieldBuilder().addBuilder(
            index, com.mwr.mercury.Message.KVPair.getDefaultInstance());
      }
      public java.util.List<com.mwr.mercury.Message.KVPair.Builder> 
           getArgsBuilderList() {
        return getArgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder> 
          getArgsFieldBuilder() {
        if (argsBuilder_ == null) {
          argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder>(
                  args_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          args_ = null;
        }
        return argsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mwr.mercury.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mwr.mercury.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes data = 1;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // optional bytes error = 2;
    boolean hasError();
    com.google.protobuf.ByteString getError();
    
    // repeated .com.mwr.mercury.KVPair structured_data = 3;
    java.util.List<com.mwr.mercury.Message.KVPair> 
        getStructuredDataList();
    com.mwr.mercury.Message.KVPair getStructuredData(int index);
    int getStructuredDataCount();
    java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
        getStructuredDataOrBuilderList();
    com.mwr.mercury.Message.KVPairOrBuilder getStructuredDataOrBuilder(
        int index);
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // optional bytes error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getError() {
      return error_;
    }
    
    // repeated .com.mwr.mercury.KVPair structured_data = 3;
    public static final int STRUCTURED_DATA_FIELD_NUMBER = 3;
    private java.util.List<com.mwr.mercury.Message.KVPair> structuredData_;
    public java.util.List<com.mwr.mercury.Message.KVPair> getStructuredDataList() {
      return structuredData_;
    }
    public java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
        getStructuredDataOrBuilderList() {
      return structuredData_;
    }
    public int getStructuredDataCount() {
      return structuredData_.size();
    }
    public com.mwr.mercury.Message.KVPair getStructuredData(int index) {
      return structuredData_.get(index);
    }
    public com.mwr.mercury.Message.KVPairOrBuilder getStructuredDataOrBuilder(
        int index) {
      return structuredData_.get(index);
    }
    
    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      error_ = com.google.protobuf.ByteString.EMPTY;
      structuredData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getStructuredDataCount(); i++) {
        if (!getStructuredData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, error_);
      }
      for (int i = 0; i < structuredData_.size(); i++) {
        output.writeMessage(3, structuredData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, error_);
      }
      for (int i = 0; i < structuredData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, structuredData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mwr.mercury.Message.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mwr.mercury.Message.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mwr.mercury.Message.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_Response_fieldAccessorTable;
      }
      
      // Construct using com.mwr.mercury.Message.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStructuredDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (structuredDataBuilder_ == null) {
          structuredData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          structuredDataBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mwr.mercury.Message.Response.getDescriptor();
      }
      
      public com.mwr.mercury.Message.Response getDefaultInstanceForType() {
        return com.mwr.mercury.Message.Response.getDefaultInstance();
      }
      
      public com.mwr.mercury.Message.Response build() {
        com.mwr.mercury.Message.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mwr.mercury.Message.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mwr.mercury.Message.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mwr.mercury.Message.Response buildPartial() {
        com.mwr.mercury.Message.Response result = new com.mwr.mercury.Message.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        if (structuredDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            structuredData_ = java.util.Collections.unmodifiableList(structuredData_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.structuredData_ = structuredData_;
        } else {
          result.structuredData_ = structuredDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mwr.mercury.Message.Response) {
          return mergeFrom((com.mwr.mercury.Message.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mwr.mercury.Message.Response other) {
        if (other == com.mwr.mercury.Message.Response.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (structuredDataBuilder_ == null) {
          if (!other.structuredData_.isEmpty()) {
            if (structuredData_.isEmpty()) {
              structuredData_ = other.structuredData_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureStructuredDataIsMutable();
              structuredData_.addAll(other.structuredData_);
            }
            onChanged();
          }
        } else {
          if (!other.structuredData_.isEmpty()) {
            if (structuredDataBuilder_.isEmpty()) {
              structuredDataBuilder_.dispose();
              structuredDataBuilder_ = null;
              structuredData_ = other.structuredData_;
              bitField0_ = (bitField0_ & ~0x00000004);
              structuredDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStructuredDataFieldBuilder() : null;
            } else {
              structuredDataBuilder_.addAllMessages(other.structuredData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getStructuredDataCount(); i++) {
          if (!getStructuredData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              error_ = input.readBytes();
              break;
            }
            case 26: {
              com.mwr.mercury.Message.KVPair.Builder subBuilder = com.mwr.mercury.Message.KVPair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStructuredData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes data = 1;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // optional bytes error = 2;
      private com.google.protobuf.ByteString error_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getError() {
        return error_;
      }
      public Builder setError(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      
      // repeated .com.mwr.mercury.KVPair structured_data = 3;
      private java.util.List<com.mwr.mercury.Message.KVPair> structuredData_ =
        java.util.Collections.emptyList();
      private void ensureStructuredDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          structuredData_ = new java.util.ArrayList<com.mwr.mercury.Message.KVPair>(structuredData_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder> structuredDataBuilder_;
      
      public java.util.List<com.mwr.mercury.Message.KVPair> getStructuredDataList() {
        if (structuredDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(structuredData_);
        } else {
          return structuredDataBuilder_.getMessageList();
        }
      }
      public int getStructuredDataCount() {
        if (structuredDataBuilder_ == null) {
          return structuredData_.size();
        } else {
          return structuredDataBuilder_.getCount();
        }
      }
      public com.mwr.mercury.Message.KVPair getStructuredData(int index) {
        if (structuredDataBuilder_ == null) {
          return structuredData_.get(index);
        } else {
          return structuredDataBuilder_.getMessage(index);
        }
      }
      public Builder setStructuredData(
          int index, com.mwr.mercury.Message.KVPair value) {
        if (structuredDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredDataIsMutable();
          structuredData_.set(index, value);
          onChanged();
        } else {
          structuredDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setStructuredData(
          int index, com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (structuredDataBuilder_ == null) {
          ensureStructuredDataIsMutable();
          structuredData_.set(index, builderForValue.build());
          onChanged();
        } else {
          structuredDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addStructuredData(com.mwr.mercury.Message.KVPair value) {
        if (structuredDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredDataIsMutable();
          structuredData_.add(value);
          onChanged();
        } else {
          structuredDataBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addStructuredData(
          int index, com.mwr.mercury.Message.KVPair value) {
        if (structuredDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredDataIsMutable();
          structuredData_.add(index, value);
          onChanged();
        } else {
          structuredDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addStructuredData(
          com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (structuredDataBuilder_ == null) {
          ensureStructuredDataIsMutable();
          structuredData_.add(builderForValue.build());
          onChanged();
        } else {
          structuredDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addStructuredData(
          int index, com.mwr.mercury.Message.KVPair.Builder builderForValue) {
        if (structuredDataBuilder_ == null) {
          ensureStructuredDataIsMutable();
          structuredData_.add(index, builderForValue.build());
          onChanged();
        } else {
          structuredDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllStructuredData(
          java.lang.Iterable<? extends com.mwr.mercury.Message.KVPair> values) {
        if (structuredDataBuilder_ == null) {
          ensureStructuredDataIsMutable();
          super.addAll(values, structuredData_);
          onChanged();
        } else {
          structuredDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearStructuredData() {
        if (structuredDataBuilder_ == null) {
          structuredData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          structuredDataBuilder_.clear();
        }
        return this;
      }
      public Builder removeStructuredData(int index) {
        if (structuredDataBuilder_ == null) {
          ensureStructuredDataIsMutable();
          structuredData_.remove(index);
          onChanged();
        } else {
          structuredDataBuilder_.remove(index);
        }
        return this;
      }
      public com.mwr.mercury.Message.KVPair.Builder getStructuredDataBuilder(
          int index) {
        return getStructuredDataFieldBuilder().getBuilder(index);
      }
      public com.mwr.mercury.Message.KVPairOrBuilder getStructuredDataOrBuilder(
          int index) {
        if (structuredDataBuilder_ == null) {
          return structuredData_.get(index);  } else {
          return structuredDataBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mwr.mercury.Message.KVPairOrBuilder> 
           getStructuredDataOrBuilderList() {
        if (structuredDataBuilder_ != null) {
          return structuredDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(structuredData_);
        }
      }
      public com.mwr.mercury.Message.KVPair.Builder addStructuredDataBuilder() {
        return getStructuredDataFieldBuilder().addBuilder(
            com.mwr.mercury.Message.KVPair.getDefaultInstance());
      }
      public com.mwr.mercury.Message.KVPair.Builder addStructuredDataBuilder(
          int index) {
        return getStructuredDataFieldBuilder().addBuilder(
            index, com.mwr.mercury.Message.KVPair.getDefaultInstance());
      }
      public java.util.List<com.mwr.mercury.Message.KVPair.Builder> 
           getStructuredDataBuilderList() {
        return getStructuredDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder> 
          getStructuredDataFieldBuilder() {
        if (structuredDataBuilder_ == null) {
          structuredDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mwr.mercury.Message.KVPair, com.mwr.mercury.Message.KVPair.Builder, com.mwr.mercury.Message.KVPairOrBuilder>(
                  structuredData_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          structuredData_ = null;
        }
        return structuredDataBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mwr.mercury.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mwr.mercury.Response)
  }
  
  public interface KVPairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // repeated bytes value = 2;
    java.util.List<com.google.protobuf.ByteString> getValueList();
    int getValueCount();
    com.google.protobuf.ByteString getValue(int index);
  }
  public static final class KVPair extends
      com.google.protobuf.GeneratedMessage
      implements KVPairOrBuilder {
    // Use KVPair.newBuilder() to construct.
    private KVPair(Builder builder) {
      super(builder);
    }
    private KVPair(boolean noInit) {}
    
    private static final KVPair defaultInstance;
    public static KVPair getDefaultInstance() {
      return defaultInstance;
    }
    
    public KVPair getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_KVPair_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mwr.mercury.Message.internal_static_com_mwr_mercury_KVPair_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> value_;
    public java.util.List<com.google.protobuf.ByteString>
        getValueList() {
      return value_;
    }
    public int getValueCount() {
      return value_.size();
    }
    public com.google.protobuf.ByteString getValue(int index) {
      return value_.get(index);
    }
    
    private void initFields() {
      key_ = "";
      value_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeBytes(2, value_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(value_.get(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mwr.mercury.Message.KVPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.KVPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mwr.mercury.Message.KVPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mwr.mercury.Message.KVPair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mwr.mercury.Message.KVPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_KVPair_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mwr.mercury.Message.internal_static_com_mwr_mercury_KVPair_fieldAccessorTable;
      }
      
      // Construct using com.mwr.mercury.Message.KVPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mwr.mercury.Message.KVPair.getDescriptor();
      }
      
      public com.mwr.mercury.Message.KVPair getDefaultInstanceForType() {
        return com.mwr.mercury.Message.KVPair.getDefaultInstance();
      }
      
      public com.mwr.mercury.Message.KVPair build() {
        com.mwr.mercury.Message.KVPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mwr.mercury.Message.KVPair buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mwr.mercury.Message.KVPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mwr.mercury.Message.KVPair buildPartial() {
        com.mwr.mercury.Message.KVPair result = new com.mwr.mercury.Message.KVPair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mwr.mercury.Message.KVPair) {
          return mergeFrom((com.mwr.mercury.Message.KVPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mwr.mercury.Message.KVPair other) {
        if (other == com.mwr.mercury.Message.KVPair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              ensureValueIsMutable();
              value_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // repeated bytes value = 2;
      private java.util.List<com.google.protobuf.ByteString> value_ = java.util.Collections.emptyList();;
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          value_ = new java.util.ArrayList<com.google.protobuf.ByteString>(value_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      public int getValueCount() {
        return value_.size();
      }
      public com.google.protobuf.ByteString getValue(int index) {
        return value_.get(index);
      }
      public Builder setValue(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureValueIsMutable();
        super.addAll(values, value_);
        onChanged();
        return this;
      }
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mwr.mercury.KVPair)
    }
    
    static {
      defaultInstance = new KVPair(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mwr.mercury.KVPair)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mwr_mercury_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mwr_mercury_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mwr_mercury_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mwr_mercury_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mwr_mercury_KVPair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mwr_mercury_KVPair_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\017com.mwr.mercury\"S\n\007Requ" +
      "est\022\017\n\007section\030\001 \001(\t\022\020\n\010function\030\002 \001(\t\022%" +
      "\n\004args\030\003 \003(\0132\027.com.mwr.mercury.KVPair\"Y\n" +
      "\010Response\022\014\n\004data\030\001 \001(\014\022\r\n\005error\030\002 \001(\014\0220" +
      "\n\017structured_data\030\003 \003(\0132\027.com.mwr.mercur" +
      "y.KVPair\"$\n\006KVPair\022\013\n\003key\030\001 \002(\t\022\r\n\005value" +
      "\030\002 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mwr_mercury_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mwr_mercury_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mwr_mercury_Request_descriptor,
              new java.lang.String[] { "Section", "Function", "Args", },
              com.mwr.mercury.Message.Request.class,
              com.mwr.mercury.Message.Request.Builder.class);
          internal_static_com_mwr_mercury_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mwr_mercury_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mwr_mercury_Response_descriptor,
              new java.lang.String[] { "Data", "Error", "StructuredData", },
              com.mwr.mercury.Message.Response.class,
              com.mwr.mercury.Message.Response.Builder.class);
          internal_static_com_mwr_mercury_KVPair_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mwr_mercury_KVPair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mwr_mercury_KVPair_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.mwr.mercury.Message.KVPair.class,
              com.mwr.mercury.Message.KVPair.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
